### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'append'

### ISSUE THREAD

**Issue by chenzhao12** [schmeing/gapless#11]
gapless.py extend -p gapless gapless_extending_reads.paf
0:00:15.342579 Preparing data from files
0:13:51.708704 Searching for extensions
Traceback (most recent call last):
  File "/home/zhuchenzhao/miniconda3/bin/gapless.py", line 13327, in <module>
    main(sys.argv[1:])
  File "/home/zhuchenzhao/miniconda3/bin/gapless.py", line 13193, in main
    GaplessExtend(args[0], prefix, min_length_contig_break)
  File "/home/zhuchenzhao/miniconda3/bin/gapless.py", line 9610, in GaplessExtend
    scaffold_paths, polishing_reads, extension_info, gap_scaffolds = ExtendScaffolds(scaffold_paths, polishing_reads, extensions, hap_merger, new_scaffolds, mappings, min_num_reads, max_mapping_uncertainty, min_scaf_len, ploidy, polishing_coverage)
  File "/home/zhuchenzhao/miniconda3/bin/gapless.py", line 9515, in ExtendScaffolds
    scaffold_paths = scaffold_paths.append( extending_reads[['scaf','pos','type']+[f'{n}{h}' for h in range(ploidy) for n in ['phase','name','start','end','strand']]+['sdist_left','sdist_right']] )
  File "/home/zhuchenzhao/miniconda3/lib/python3.9/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'append'

**Comment by JhinAir** [comment]
same issue here. Has it been solved?

**Comment by JhinAir** [comment]
It's an issue of 'pipeline crashed: extend'. Could you please help check it out?@schmeing

**Comment by ashleyp1** [comment]
I also just experienced this same issue

**Comment by bennuru** [comment]
The 'append' issue is probably related to pandas version. Try with pandas 1.5.3 as 'append' has been removed from pandas>=2.0.

**Comment by YocelynG** [comment]
I ran into the same error. It looks like some files did not generated in the previous steps.
I fixed it by running the pipeline step by step with some modifications:

gapless.py split -o gapless_split.fa assembly_hifiasm_ctg.fasta
minimap2 -t 30 -DP -k19 -w19 -m200 gapless_split.fa gapless_split.fa > gapless_split_repeats.paf
minimap2 -t 30 -x map-hifi -c -N 5 --secondary=no gapless_split.fa hifi_reads.default.filt.fastq.gz > gapless_reads.paf
gapless.py scaffold -p gapless -s gapless_stats.pdf gapless_split.fa gapless_reads.paf gapless_split_repeats.paf
minimap2 -t 30 -x map-hifi  <(seqtk subseq hifi_reads.default.filt.fastq.gz gapless_extending_reads.lst) <(seqtk subseq hifi_reads.default.filt.fastq.gz gapless_extending_reads.lst) > gapless_extending_reads.paf
gapless.py extend -p gapless gapless_extending_reads.paf
seqtk subseq hifi_reads.default.filt.fastq.gz gapless_used_reads.lst > temp_finish.fastq

##Here the option -p is not indicated in the documentation

gapless.py finish -o gapless_raw.fa -H 0 -s gapless_extended_scaffold_paths.csv -p gapless_polishing.csv gapless_split.fa temp_finish.fastq
minimap2 -t 30 -x map-hifi gapless_raw.fa hifi_reads.default.filt.fastq.gz > gapless_consensus.paf
racon -t 30 hifi_reads.default.filt.fastq.gz gapless_consensus.paf gapless_raw.fa > gapless.fa
