### ISSUE TITLE
pipeline crashed : scaffold (numpy.core._exceptions._ArrayMemoryError)

### ISSUE THREAD

**Issue by jaehakson** [schmeing/gapless#14]
I had an issue on the scaffolding step; probably allocating memory....
But I do not understand because the node I used is allocated 256Gb memory. 

Below is the error message I have got from 'gapless_scaffold.log' without an option '--largeGenome'
0:00:05.183697 Reading in original assembly
0:00:06.559198 Loading repeats
0:00:13.782595 Filtering mappings
0:00:54.308255 Search for possible break points
Traceback (most recent call last):
  File "/home/js3054/.local/bin/gapless.py", line 13362, in <module>
    main(sys.argv[1:])
  File "/home/js3054/.local/bin/gapless.py", line 13189, in main
    GaplessScaffold(args[0], args[1], args[2], min_mapq, min_mapping_length, min_length_contig_break, large_reads, large_contigs, prefix, stats)
  File "/home/js3054/.local/bin/gapless.py", line 9107, in GaplessScaffold
    mappings = UpdateMappingsToContigParts(mappings, contig_parts, min_mapping_length, max_dist_contig_end, min_extension)
  File "/home/js3054/.local/bin/gapless.py", line 1182, in UpdateMappingsToContigParts
    mappings = GetContigPartFromTargetID(mappings, contig_parts, min_mapping_length)
  File "/home/js3054/.local/bin/gapless.py", line 1177, in GetContigPartFromTargetID
    mappings = mappings[(mappings['t_start']+min_mapping_length < mappings['part_end']) & (mappings['t_end']-min_mapping_length > mappings['part_start'])].copy()
  File "/home/js3054/miniconda3/envs/gapless/lib/python3.10/site-packages/pandas/core/frame.py", line 3496, in __getitem__
    return self._getitem_bool_array(key)
  File "/home/js3054/miniconda3/envs/gapless/lib/python3.10/site-packages/pandas/core/frame.py", line 3551, in _getitem_bool_array
    return self._take_with_is_copy(indexer, axis=0)
  File "/home/js3054/miniconda3/envs/gapless/lib/python3.10/site-packages/pandas/core/generic.py", line 3716, in _take_with_is_copy
    result = self.take(indices=indices, axis=axis)
  File "/home/js3054/miniconda3/envs/gapless/lib/python3.10/site-packages/pandas/core/generic.py", line 3701, in take
    self._consolidate_inplace()
  File "/home/js3054/miniconda3/envs/gapless/lib/python3.10/site-packages/pandas/core/generic.py", line 5653, in _consolidate_inplace
    self._protect_consolidate(f)
  File "/home/js3054/miniconda3/envs/gapless/lib/python3.10/site-packages/pandas/core/generic.py", line 5641, in _protect_consolidate
    result = f()
  File "/home/js3054/miniconda3/envs/gapless/lib/python3.10/site-packages/pandas/core/generic.py", line 5651, in f
    self._mgr = self._mgr.consolidate()
  File "/home/js3054/miniconda3/envs/gapless/lib/python3.10/site-packages/pandas/core/internals/managers.py", line 631, in consolidate
    bm._consolidate_inplace()
  File "/home/js3054/miniconda3/envs/gapless/lib/python3.10/site-packages/pandas/core/internals/managers.py", line 1685, in _consolidate_inplace
    self.blocks = tuple(_consolidate(self.blocks))
  File "/home/js3054/miniconda3/envs/gapless/lib/python3.10/site-packages/pandas/core/internals/managers.py", line 2084, in _consolidate
    merged_blocks = _merge_blocks(
  File "/home/js3054/miniconda3/envs/gapless/lib/python3.10/site-packages/pandas/core/internals/managers.py", line 2118, in _merge_blocks
    new_values = new_values[argsort]
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 74.3 GiB for an array with shape (9, 1108714767) and data type int64

Below is the error message I have got from 'gapless_scaffold.log' with an option '--largeGenome'
0:00:04.748569 Reading in original assembly
0:00:06.579180 Loading repeats
0:00:14.159905 Filtering mappings
0:00:55.106829 Search for possible break points
Traceback (most recent call last):
  File "/home/js3054/.local/bin/gapless.py", line 13362, in <module>
    main(sys.argv[1:])
  File "/home/js3054/.local/bin/gapless.py", line 13189, in main
    GaplessScaffold(args[0], args[1], args[2], min_mapq, min_mapping_length, min_length_contig_break, large_reads, large_contigs, prefix, stats)
  File "/home/js3054/.local/bin/gapless.py", line 9098, in GaplessScaffold
    break_groups, repeat_removal, spurious_break_indexes, non_informative_mappings, unconnected_breaks = FindBreakPoints(mappings, contigs, covered_regions, repeats, max_dist_contig_end, min_mapping_length, min_length_contig_break, max_break_point_distance, min_num_reads, min_extension, merge_block_length, org_scaffold_trust, cov_probs, prob_factor, allow_same_contig_breaks, prematurity_threshold, pdf)
  File "/home/js3054/.local/bin/gapless.py", line 975, in FindBreakPoints
    break_points, unconnected_break_points = CountAndApplyBreakVetos(break_points, mappings, pot_breaks, bp_ext_len, cov_probs, covered_regions, repeats, max_dist_contig_end, max_break_point_distance, min_mapping_length, min_num_reads, min_length_contig_break, prob_factor, merge_block_length, prematurity_threshold)
  File "/home/js3054/.local/bin/gapless.py", line 843, in CountAndApplyBreakVetos
    breaks_in_repeats = breaks_in_repeats[ (breaks_in_repeats['lrep_len'] > 0) | (breaks_in_repeats['rrep_len'] > 0) ].copy()
  File "/home/js3054/miniconda3/envs/gapless/lib/python3.10/site-packages/pandas/core/frame.py", line 3496, in __getitem__
    return self._getitem_bool_array(key)
  File "/home/js3054/miniconda3/envs/gapless/lib/python3.10/site-packages/pandas/core/frame.py", line 3551, in _getitem_bool_array
    return self._take_with_is_copy(indexer, axis=0)
  File "/home/js3054/miniconda3/envs/gapless/lib/python3.10/site-packages/pandas/core/generic.py", line 3716, in _take_with_is_copy
    result = self.take(indices=indices, axis=axis)
  File "/home/js3054/miniconda3/envs/gapless/lib/python3.10/site-packages/pandas/core/generic.py", line 3701, in take
    self._consolidate_inplace()
  File "/home/js3054/miniconda3/envs/gapless/lib/python3.10/site-packages/pandas/core/generic.py", line 5653, in _consolidate_inplace
    self._protect_consolidate(f)
  File "/home/js3054/miniconda3/envs/gapless/lib/python3.10/site-packages/pandas/core/generic.py", line 5641, in _protect_consolidate
    result = f()
  File "/home/js3054/miniconda3/envs/gapless/lib/python3.10/site-packages/pandas/core/generic.py", line 5651, in f
    self._mgr = self._mgr.consolidate()
  File "/home/js3054/miniconda3/envs/gapless/lib/python3.10/site-packages/pandas/core/internals/managers.py", line 631, in consolidate
    bm._consolidate_inplace()
  File "/home/js3054/miniconda3/envs/gapless/lib/python3.10/site-packages/pandas/core/internals/managers.py", line 1685, in _consolidate_inplace
    self.blocks = tuple(_consolidate(self.blocks))
  File "/home/js3054/miniconda3/envs/gapless/lib/python3.10/site-packages/pandas/core/internals/managers.py", line 2084, in _consolidate
    merged_blocks = _merge_blocks(
  File "/home/js3054/miniconda3/envs/gapless/lib/python3.10/site-packages/pandas/core/internals/managers.py", line 2118, in _merge_blocks
    new_values = new_values[argsort]
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 98.7 GiB for an array with shape (6, 2207565873) and data type int64

**Comment by pbpearman** [comment]
OS and Kernel info:
Operating System: Rocky Linux 8.9 (Green Obsidian)
       CPE OS Name: cpe:/o:rocky:rocky:8:GA
            Kernel: Linux 4.18.0-513.18.1.el8_9.x86_64

I get a very similar error, a numby.core_exception.  I requested 60 cores and 770GB in the slurm job submission, and got no OOM error (see below).  However the array memory error references a matrix that is (5, 9126501301).  The numby.core_exceptions line is at the bottom of this gapless_scaffold.log dump:

[bgppermp@agamede logs]$ more gapless_scaffold.log 
/home/bgppermp/gscratch/conda/env/gapless_env/bin/gapless.py:245: UserWarning: 

`distplot` is a deprecated function and will be removed in seaborn v0.14.0.

Please adapt your code to use either `displot` (a figure-level function with
similar flexibility) or `histplot` (an axes-level function for histograms).

For a guide to updating your code to use the new functions, please see
https://gist.github.com/mwaskom/de44147ed2974457ad6372750bbe5751

  ax = sns.distplot(values, bins=100, kde=False)
/home/bgppermp/gscratch/conda/env/gapless_env/bin/gapless.py:245: UserWarning: 

`distplot` is a deprecated function and will be removed in seaborn v0.14.0.

Please adapt your code to use either `displot` (a figure-level function with
similar flexibility) or `histplot` (an axes-level function for histograms).

For a guide to updating your code to use the new functions, please see
https://gist.github.com/mwaskom/de44147ed2974457ad6372750bbe5751

  ax = sns.distplot(values, bins=100, kde=False)
/home/bgppermp/gscratch/conda/env/gapless_env/bin/gapless.py:245: UserWarning: 

`distplot` is a deprecated function and will be removed in seaborn v0.14.0.

Please adapt your code to use either `displot` (a figure-level function with
similar flexibility) or `histplot` (an axes-level function for histograms).

For a guide to updating your code to use the new functions, please see
https://gist.github.com/mwaskom/de44147ed2974457ad6372750bbe5751

  ax = sns.distplot(values, bins=100, kde=False)
/home/bgppermp/gscratch/conda/env/gapless_env/bin/gapless.py:253: UserWarning: set_ticklabels() should only be used with a fixed number of ticks, i.e. after set_t
icks() or using a FixedLocator.
  ax.set(xticklabels=np.where(locs.astype(int) == locs, (10 ** locs).astype(str), ""))
/home/bgppermp/gscratch/conda/env/gapless_env/bin/gapless.py:245: UserWarning: 

`distplot` is a deprecated function and will be removed in seaborn v0.14.0.

Please adapt your code to use either `displot` (a figure-level function with
similar flexibility) or `histplot` (an axes-level function for histograms).

For a guide to updating your code to use the new functions, please see
https://gist.github.com/mwaskom/de44147ed2974457ad6372750bbe5751

  ax = sns.distplot(values, bins=100, kde=False)
/home/bgppermp/gscratch/conda/env/gapless_env/bin/gapless.py:253: UserWarning: set_ticklabels() should only be used with a fixed number of ticks, i.e. after set_t
icks() or using a FixedLocator.
  ax.set(xticklabels=np.where(locs.astype(int) == locs, (10 ** locs).astype(str), ""))
/home/bgppermp/gscratch/conda/env/gapless_env/bin/gapless.py:598: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a 
future version of pandas. Value '[ 1260   529  1661 ... 71457  2243 10087]' has dtype incompatible with int32, please explicitly cast to a compatible dtype first.
  cur_mappings.loc[cur_mappings['strand'] == '-', ['q_left','q_right']] = cur_mappings.loc[cur_mappings['strand'] == '-', ['q_right','q_left']].values # Switch th
e values in case of negative strand, so that they represent the extension on the left/right side of the break after mapping ends
/home/bgppermp/gscratch/conda/env/gapless_env/bin/gapless.py:245: UserWarning: 

`distplot` is a deprecated function and will be removed in seaborn v0.14.0.

Please adapt your code to use either `displot` (a figure-level function with
similar flexibility) or `histplot` (an axes-level function for histograms).

For a guide to updating your code to use the new functions, please see
https://gist.github.com/mwaskom/de44147ed2974457ad6372750bbe5751

  ax = sns.distplot(values, bins=100, kde=False)
/home/bgppermp/gscratch/conda/env/gapless_env/bin/gapless.py:253: UserWarning: set_ticklabels() should only be used with a fixed number of ticks, i.e. after set_t
icks() or using a FixedLocator.
  ax.set(xticklabels=np.where(locs.astype(int) == locs, (10 ** locs).astype(str), ""))
0:00:01.145882 Reading in original assembly
0:00:05.490426 Loading repeats
0:09:55.856302 Filtering mappings
0:11:42.370557 Search for possible break points
Traceback (most recent call last):
  File "/home/bgppermp/gscratch/conda/env/gapless_env/bin/gapless.py", line 13327, in <module>
    main(sys.argv[1:])
  File "/home/bgppermp/gscratch/conda/env/gapless_env/bin/gapless.py", line 13156, in main
    GaplessScaffold(args[0], args[1], args[2], min_mapq, min_mapping_length, min_length_contig_break, prefix, stats)
  File "/home/bgppermp/gscratch/conda/env/gapless_env/bin/gapless.py", line 9078, in GaplessScaffold
    break_groups, repeat_removal, spurious_break_indexes, non_informative_mappings, unconnected_breaks = FindBreakPoints(mappings, contigs, covered_regions, repea
ts, max_dist_contig_end, min_mapping_length, min_length_contig_break, max_break_point_distance, min_num_reads, min_extension, merge_block_length, org_scaffold_tru
st, cov_probs, prob_factor, allow_same_contig_breaks, prematurity_threshold, pdf)
                                                                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bgppermp/gscratch/conda/env/gapless_env/bin/gapless.py", line 955, in FindBreakPoints
    repeat_removal = IdentifyBreakinsRepeats(break_points, mappings, repeats, min_num_reads, max_dist_contig_end, min_mapping_length, min_length_contig_break, mer
ge_block_length)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^^^^^^^^^^^^^
  File "/home/bgppermp/gscratch/conda/env/gapless_env/bin/gapless.py", line 702, in IdentifyBreakinsRepeats
    bmap = inner_repeats.merge(bmap, on=['contig_id','block'], how='inner')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bgppermp/gscratch/conda/env/gapless_env/lib/python3.12/site-packages/pandas/core/frame.py", line 10832, in merge
    return merge(
           ^^^^^^
  File "/home/bgppermp/gscratch/conda/env/gapless_env/lib/python3.12/site-packages/pandas/core/reshape/merge.py", line 184, in merge
    return op.get_result(copy=copy)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bgppermp/gscratch/conda/env/gapless_env/lib/python3.12/site-packages/pandas/core/reshape/merge.py", line 888, in get_result
    result = self._reindex_and_concat(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bgppermp/gscratch/conda/env/gapless_env/lib/python3.12/site-packages/pandas/core/reshape/merge.py", line 863, in _reindex_and_concat
    rmgr = right._mgr.reindex_indexer(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bgppermp/gscratch/conda/env/gapless_env/lib/python3.12/site-packages/pandas/core/internals/managers.py", line 688, in reindex_indexer
    blk.take_nd(
  File "/home/bgppermp/gscratch/conda/env/gapless_env/lib/python3.12/site-packages/pandas/core/internals/blocks.py", line 1307, in take_nd
    new_values = algos.take_nd(
                 ^^^^^^^^^^^^^^
  File "/home/bgppermp/gscratch/conda/env/gapless_env/lib/python3.12/site-packages/pandas/core/array_algos/take.py", line 117, in take_nd
    return _take_nd_ndarray(arr, indexer, axis, fill_value, allow_fill)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bgppermp/gscratch/conda/env/gapless_env/lib/python3.12/site-packages/pandas/core/array_algos/take.py", line 157, in _take_nd_ndarray
    out = np.empty(out_shape, dtype=dtype)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
**numpy.core._exceptions._ArrayMemoryError: Unable to allocate 170. GiB for an array with shape (5, 9126501301) and data type int32**

It would be great to hear if you think this is a machine limitation or something in the gapless script.  There was no OOM error in the script output:
gscratch]$ more slurm-52786.out 
Job runing on na10
Choosing scratch ...
Automatic scratch folder selection
/scratch/bgppermp/52786
/scratch/bgppermp/52786 directory
cp {{files}} to  /scratch/bgppermp/52786/.
pipeline crashed : scaffold
srun: error: na10: task 0: Exited with exit code 1
srun: Terminating StepId=52786.0
real 170852.62
user 0.00
sys 0.00
Recovering execution output...
Moving from /scratch/bgppermp/52786 to /beegfs_agamede/gscratch/bgppermp/arina.52786
mkdir -p /beegfs_agamede/gscratch/bgppermp/arina.52786
mv /scratch/bgppermp/52786/* /beegfs_agamede/gscratch/bgppermp/arina.52786

Job FINISHED (successfully or not). Performing cleanup...

Recover execution output
recover
Recovering execution output...
Moving from /scratch/bgppermp/52786 to /beegfs_agamede/gscratch/bgppermp/arina.52786
mkdir -p /beegfs_agamede/gscratch/bgppermp/arina.52786
mv /scratch/bgppermp/52786/* /beegfs_agamede/gscratch/bgppermp/arina.52786
mv: cannot stat '/scratch/bgppermp/52786/*': No such file or directory

Any thoughts would be greatly appreciated.  I'm not sure about the significance of the 'breakpoint' notifications in this situation either.
Peter
