### ISSUE TITLE
Issue with gapless.py extend

### ISSUE THREAD

**Issue by pclee2007** [schmeing/gapless#17]
Hi,
I got an error in running gapless.sh (in the step of gapless.py extend);

logs/gapless_extend.log describes the following error,
 "Traceback (most recent call last):
  File "/analysis/program/gapless.py", line 13362, in <module>
    main(sys.argv[1:])
  File "/analysis/program/gapless.py", line 13228, in main
    GaplessExtend(args[0], prefix, min_length_contig_break, large_reads)
UnboundLocalError: local variable 'large_reads' referenced before assignment"

Thanks,
Pyung Cheon

**Comment by SaelinB** [comment]
I had the same issue and solved it by using the conda installation with python 3.9.6 and pandas 1.5.3

**Comment by Dogrinev** [comment]
Posted an alternative solution to this in https://github.com/schmeing/gapless/issues/18#issuecomment-1910497051
